spring.application.name=service-registry
server.port=${SERVICE_REGISTRY_PORT:8761}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.service.with-time-in-ns-when-sync-empty=0
