spring.application.name=api-gateway
server.port=${API_GATEWAY_PORT:8084}

logging.level.org.springframework.cloud.gateway=${API_GATEWAY_LOG_LEVEL:TRACE}
spring.cloud.loadbalancer.cache.ttl=${API_GATEWAY_CACHE_TTL:5s}

eureka.client.service-url.defaultZone=${SERVICE_REGISTRY_URL:http://localhost:8761/eureka}
eureka.client.registry-fetch-interval-seconds=${SERVICE_REGISTRY_CLIENT_FETCH_INTERVAL_SECONDS:5}
eureka.instance.lease-renewal-interval-in-seconds=${SERVICE_REGISTRY_CLIENT_LEASE_RENEWAL_INTERVAL_SECONDS:5}
