spring.application.name=resource-processor

eureka.client.service-url.defaultZone=${SERVICE_REGISTRY_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=${SERVICE_REGISTRY_PREFER_IP:false}
eureka.instance.hostname=${SERVICE_REGISTRY_INSTANCE_HOSTNAME:localhost}
