spring.application.name=song-service
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/song-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=none

eureka.client.service-url.defaultZone=${SERVICE_REGISTRY_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=${SERVICE_REGISTRY_PREFER_IP:false}
eureka.instance.hostname=${SERVICE_REGISTRY_INSTANCE_HOSTNAME:localhost}

management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
loki.url=${LOKI_URL:http://localhost:3100}
