apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: zipkin
          matcherRegex: "traceId=([0-9a-f]{16,32})"
          name: TraceID
          url: "$${__value.raw}"

  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://zipkin:9411
    uid: zipkin
