spring.application.name=resource-service
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resource-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=none

song-service.url=${API_GATEWAY_URL:http://localhost:8081}

eureka.client.service-url.defaultZone=${SERVICE_REGISTRY_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=${SERVICE_REGISTRY_PREFER_IP:false}
eureka.instance.hostname=${SERVICE_REGISTRY_INSTANCE_HOSTNAME:localhost}
